# Generated by Django 6.1 on 2026-08-19 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('terminal', models.CharField(max_length=120)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('a_bordo', 'A bordo'), ('despegado', 'Despegado'), ('retrasado', 'Retrasado'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='gestion.gate')),
            ],
        ),
    ]
